{% set name = "elementable" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb7b64dbb8b5f56f07072abf3e4418e52e5a983c59a56282bab1bb1b2fc84fd3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - elementable
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/lilyminium/elementable
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Flexible, extensible elements package'
  description: |
    elementable is a package to create elements for use in other
    packages. It is designed to generate elements compatible with
    several units packages and base classes; it accepts arbitrary
    input data with arbitrary attributes, to allow for data
    customization by each package.
  doc_url: https://elementable.readthedocs.io/
  dev_url: https://github.com/lilyminium/elementable

extra:
  recipe-maintainers:
    - lilyminium
